%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.5.0

-ifndef(simple).
-define(simple, true).

-define(simple_gpb_version, "4.5.0").

-ifndef('SIMPLE_PB_H').
-define('SIMPLE_PB_H', true).
-record('Simple',
        {id = 0                 :: integer() | undefined, % = 1, 32 bits
         id2 = 0                :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
