// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: da_message.proto

#ifndef PROTOBUF_INCLUDED_da_5fmessage_2eproto
#define PROTOBUF_INCLUDED_da_5fmessage_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_da_5fmessage_2eproto 

namespace protobuf_da_5fmessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_da_5fmessage_2eproto
class da_record;
class da_recordDefaultTypeInternal;
extern da_recordDefaultTypeInternal _da_record_default_instance_;
namespace google {
namespace protobuf {
template<> ::da_record* Arena::CreateMaybeMessage<::da_record>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class da_record : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:da_record) */ {
 public:
  da_record();
  virtual ~da_record();

  da_record(const da_record& from);

  inline da_record& operator=(const da_record& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  da_record(da_record&& from) noexcept
    : da_record() {
    *this = ::std::move(from);
  }

  inline da_record& operator=(da_record&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const da_record& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const da_record* internal_default_instance() {
    return reinterpret_cast<const da_record*>(
               &_da_record_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(da_record* other);
  friend void swap(da_record& a, da_record& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline da_record* New() const final {
    return CreateMaybeMessage<da_record>(NULL);
  }

  da_record* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<da_record>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const da_record& from);
  void MergeFrom(const da_record& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(da_record* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 a = 1;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::uint32 a() const;
  void set_a(::google::protobuf::uint32 value);

  // uint32 b = 2;
  void clear_b();
  static const int kBFieldNumber = 2;
  ::google::protobuf::uint32 b() const;
  void set_b(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:da_record)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 a_;
  ::google::protobuf::uint32 b_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_da_5fmessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// da_record

// uint32 a = 1;
inline void da_record::clear_a() {
  a_ = 0u;
}
inline ::google::protobuf::uint32 da_record::a() const {
  // @@protoc_insertion_point(field_get:da_record.a)
  return a_;
}
inline void da_record::set_a(::google::protobuf::uint32 value) {
  
  a_ = value;
  // @@protoc_insertion_point(field_set:da_record.a)
}

// uint32 b = 2;
inline void da_record::clear_b() {
  b_ = 0u;
}
inline ::google::protobuf::uint32 da_record::b() const {
  // @@protoc_insertion_point(field_get:da_record.b)
  return b_;
}
inline void da_record::set_b(::google::protobuf::uint32 value) {
  
  b_ = value;
  // @@protoc_insertion_point(field_set:da_record.b)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_da_5fmessage_2eproto
