%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.1

-ifndef(da_message).
-define(da_message, true).

-define(da_message_gpb_version, "4.4.1").

-ifndef('DA_RECORD_PB_H').
-define('DA_RECORD_PB_H', true).
-record(da_record,
        {a = 0                  :: non_neg_integer() | undefined, % = 1, 32 bits
         b = 0                  :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
