%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.7.2

-ifndef(stvlist).
-define(stvlist, true).

-define(stvlist_gpb_version, "4.7.2").

-ifndef('STVLIST_PB_H').
-define('STVLIST_PB_H', true).
-record(stvlist,
        {tvid = <<>>            :: iodata() | undefined, % = 1
         ids = []               :: [non_neg_integer()] | undefined % = 2, 32 bits
        }).
-endif.

-endif.
